openapi: "3.0.0"
info:
  title: "exam-api"
  description: "API for managing exams"
  version: "1.0.0"
paths:
  /categories:
    get:
      summary: "Get all categories"
      responses:
        '200':
          description: "Successful response"
          content:
            application/json:
              schema:
                type: "array"
                items:
                  $ref: "#/components/schemas/Category"
    post:
      summary: "Create a new category"
      responses:
        '201':
          description: "Category created successfully"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Category"
components:
  schemas:
    Category:
      type: "object"
      properties:
        id:
          type: "integer"
        name:
          type: "string"
